tls-docs-examples
mulesoft/docs-gateway pull request #210
Opened 2023-03-20 14:01 UTC by aneisen-mulesoft

# Writer's Quality Checklist

Before merging your PR, did you:

- [ ] Run spell checker
- [ ] Run link checker to check for broken xrefs
- [ ] Check for orphan files
- [ ] Perform a local build and do a final visual check of your content, including checking for:
  - Broken images
  - Dead links
  - Correct rendering of partials if they are used in your content
  - Formatting issues, such as:
    - Misnumbered ordered lists (steps) or incorrectly nested unordered lists
    - Messed up tables
    - Proper indentation
    - Correct header levels
- [ ] Receive final review and signoff from:
  - Technical SME
  - Product Manager
  - Editor or peer reviewer
  - Reporter, if this content is in response to a reported issue (internal or external feedback)
- [ ] If applicable, verify that the software actually got released

2023-03-20 16:20 UTC, balbifm requested changes

2023-03-20 16:20 UTC, balbifm commented on gateway/1.4/modules/ROOT/pages/_partials/task-tls-config.adoc
> +*Sample configuration for one way outbound TLS::*
This is mTLS

2023-03-20 16:53 UTC, chris-campbell9 commented on gateway/1.4/modules/ROOT/pages/_partials/task-tls-config.adoc
> +*Sample configuration for adding outbound TLS with no certificate validation::*
```suggestion
*Sample configuration for adding outbound TLS with no certificate validation:*
```

2023-03-20 16:53 UTC, chris-campbell9 commented on gateway/1.4/modules/ROOT/pages/_partials/task-tls-config.adoc
> +*Sample configuration for one way outbound TLS::*
```suggestion
*Sample configuration for one-way outbound TLS:*
```

2023-03-20 16:54 UTC, chris-campbell9 commented on gateway/1.4/modules/ROOT/pages/_partials/task-tls-config.adoc
> +*Sample configuration for one way outbound TLS::*
```suggestion
*Sample configuration for one-way outbound TLS:*
```

2023-03-20 17:05 UTC, aneisen-mulesoft commented on gateway/1.4/modules/ROOT/pages/_partials/task-tls-config.adoc
> +*Sample configuration for one way outbound TLS::*
fixed

2023-03-20 17:30 UTC, balbifm requested changes

2023-03-20 17:30 UTC, balbifm commented on gateway/1.4/modules/ROOT/pages/_partials/task-tls-config.adoc
> +*Sample configuration for one-way outbound mTLS:*
"one-way outbound" and mTLS are mutually exclusive. In fact, mTLS and "two-way TLS" are interchangeable keywords. Should probably just be "Sample configuration for mTLS"

2023-03-20 18:52 UTC, garciarodrigor commented on policies/modules/ROOT/pages/policies-included-tls-outbound.adoc
>  | Required
That should be `Optional` in outbound TLS, but `Required` for inbound TLS, because we can't setup the listener in TLS mode without setting the certificate (key + crt), instead we can configure the upstream to talk with an TLS server without adding that, we need to add this section in a upstream only when we try to setup mTLS

2023-03-20 18:52 UTC, garciarodrigor commented on policies/modules/ROOT/pages/policies-included-tls-outbound.adoc
> +| Optional
That is `Required`

2023-04-06 18:50 UTC, chris-campbell9 commented
Hi @aneisen-mulesoft, I just committed a change to this branch that moves one of the pages you're modifying. This is why there's a merge conflict. The new location of the page is:
https://github.com/mulesoft/docs-gateway/blob/get-well-staging-branch/gateway/1.4/modules/ROOT/pages/policies-included-tls-outbound.adoc

2023-05-22 23:01 UTC, chris-campbell9 commented
Hi @aneisen-mulesoft, is this PR still an open issue? If so, the files have moved. Also, can you prepend a GUS ID to the subject of this PR? We're being asked to include GUS ID's so we can trace contributions.

2023-05-22 23:43 UTC, dukesphere commented
@aneisen-mulesoft  Would you please create a GUS work item for this so we can trace it and keep track of the rationale for the changes requested in the PR?

2024-07-03 23:00 UTC, chris-campbell9 commented
Closed as outdated.

2024-07-03 23:00 UTC, closed without merging