W-13791949 publish pdk to exchange gr
mulesoft/docs-gateway pull request #349
Opened 2023-07-19 20:53 UTC by glenn-rodgers-sf

# Writer's Quality Checklist

Before merging your PR, did you:

- [ ] Run spell checker
- [ ] Run link checker to check for broken xrefs
- [ ] Check for orphan files
- [ ] Perform a local build and do a final visual check of your content, including checking for:
  - Broken images
  - Dead links
  - Correct rendering of partials if they are used in your content
  - Formatting issues, such as:
    - Misnumbered ordered lists (steps) or incorrectly nested unordered lists
    - Messed up tables
    - Proper indentation
    - Correct header levels
- [ ] Receive final review and signoff from:
  - Technical SME
  - Product Manager
  - Editor or peer reviewer
  - Reporter, if this content is in response to a reported issue (internal or external feedback)
- [ ] If applicable, verify that the software actually got released

2023-07-20 17:25 UTC, NachoRaik requested changes

2023-07-20 17:25 UTC, NachoRaik commented on gateway/1.5/modules/ROOT/nav.adoc
> +**** xref:policies-pdk-publish-policies.adoc[Upload Custom Policies to Exchance]
```suggestion
**** xref:policies-pdk-publish-policies.adoc[Upload Custom Policies to Exchange]
```

2023-07-20 17:25 UTC, NachoRaik commented on gateway/1.5/modules/ROOT/pages/policies-pdk-publish-policies.adoc
> +Rerunning the publish command creates a new version of the policy asset with a updated timestamp. Previously published policy versions are still avaliable.
```suggestion
Rerunning the publish command creates a new version of the policy asset with an updated timestamp. Previously published policy versions are still avaliable.
```

2023-07-20 17:25 UTC, NachoRaik commented on gateway/1.5/modules/ROOT/pages/policies-pdk-publish-policies.adoc
> +After releaseing the asset, rerunning the publish or release command results in a conflict error.
```suggestion
After releasing the asset, rerunning the publish or release command results in a conflict error.
```

Also, the publish won't result in conflict, at the moment.

2023-07-20 17:25 UTC, NachoRaik commented on gateway/1.5/modules/ROOT/pages/policies-pdk-publish-policies.adoc
> +For example, if the latests version is `1.0.0`, update the Cargo.toml` file as follows to begin working on a minor release:
```suggestion
For example, if the latest version is `1.0.0`, update the `Cargo.toml` file as follows to begin working on a minor release:
```

2023-07-20 23:08 UTC, hannanelson commented on gateway/1.5/modules/ROOT/nav.adoc
> +**** xref:policies-pdk-publish-policies.adoc[Upload Custom Policies to Exchange]
If you leave the [] blank in xrefs, they get filled in automagically during the build - and you don't have to maintain them manually.

2023-07-20 23:08 UTC, hannanelson commented on gateway/1.5/modules/ROOT/pages/policies-pdk-publish-policies.adoc
> +When uploading your policy to Exchange you can choose to do either of the following:
```suggestion
When uploading your policy to Exchange, you can choose to either:
```

2023-07-20 23:09 UTC, hannanelson commented on gateway/1.5/modules/ROOT/pages/policies-pdk-publish-policies.adoc
> +During the custom policy development cycle, you can upload your policy to Exchange to distribute it and manage its version. For more information about Exchange, see xref:exchange::index.adoc[].
flip to put customer task (distribute/manage) first.

2023-07-20 23:11 UTC, hannanelson commented on gateway/1.5/modules/ROOT/pages/policies-pdk-publish-policies.adoc
> +To publish a custom policy, run the publish command from the policy's root folder:
Does publish need a font change?

2023-07-20 23:12 UTC, hannanelson commented on gateway/1.5/modules/ROOT/pages/policies-pdk-publish-policies.adoc
> +After publishing the asset, a new asset appears in Exchange. The asset's group ID, asset ID, and asset version (GAV) appears similar to the following:
```suggestion
After publishing the asset, a new asset appears in Exchange. The asset's group ID, asset ID, and asset version (GAV) appear, similar to the following:
```

2023-07-20 23:13 UTC, hannanelson commented on gateway/1.5/modules/ROOT/pages/policies-pdk-publish-policies.adoc
> +* *assetID*: `my-custom-policy-dev` +
Global - put the + on a line by itself (it affects the line spacing). 
https://confluence.internal.salesforce.com/display/MTDT/Formatting+with+Asciidoc#FormattingwithAsciidoc-ListContinuation(akaIndentedParagraphs)

2023-07-20 23:13 UTC, hannanelson commented on gateway/1.5/modules/ROOT/pages/policies-pdk-publish-policies.adoc
> +Rerunning the publish command creates a new version of the policy asset with an updated timestamp. Previously published policy versions are still avaliable.
```suggestion
Rerunning the publish command creates a new version of the policy asset with an updated timestamp. Previously published policy versions are still available.
```

2023-07-20 23:15 UTC, hannanelson commented on gateway/1.5/modules/ROOT/pages/policies-pdk-publish-policies.adoc
> +Rerunning the publish command creates a new version of the policy asset with an updated timestamp. Previously published policy versions are still avaliable.
Should publish be mono bold?
https://confluence.internal.salesforce.com/display/MTDT/MuleSoft+CX+Writing+Style+Reference#MuleSoftCXWritingStyleReference-boldfont

2023-07-20 23:15 UTC, hannanelson commented on gateway/1.5/modules/ROOT/pages/policies-pdk-publish-policies.adoc
> +Rerunning the publish command creates a new version of the policy asset with an updated timestamp. Previously published policy versions are still avaliable.
Make sure to run vale!

2023-07-20 23:16 UTC, hannanelson commented on gateway/1.5/modules/ROOT/pages/policies-pdk-publish-policies.adoc
> +To release a custom policy, run the release command from the policy's root folder:
mono bold?

2023-07-20 23:16 UTC, hannanelson commented on gateway/1.5/modules/ROOT/pages/policies-pdk-publish-policies.adoc
> +After releasing the asset in Exchange, the asset's GAV appears similar to the following:
```suggestion
After releasing the asset in Exchange, the asset's GAV appears, similar to the following:
```

2023-07-20 23:16 UTC, hannanelson commented on gateway/1.5/modules/ROOT/pages/policies-pdk-publish-policies.adoc
> +After releaseing the asset, rerunning the publish command results in a conflict error.
mono bold

2023-07-20 23:16 UTC, hannanelson approved these changes

2023-07-21 15:11 UTC, glenn-rodgers-sf commented on gateway/1.5/modules/ROOT/nav.adoc
> +**** xref:policies-pdk-publish-policies.adoc[Upload Custom Policies to Exchange]
Ok, yeah, I was confused by this.

I'm under the impression that we use Gerunds in the titles but imperative mood in the sidebar. Leaving the xref blank would apply the gerunds to the sidebar. Do we have any docs on this?

2023-07-21 15:30 UTC, hannanelson commented on gateway/1.5/modules/ROOT/nav.adoc
> +**** xref:policies-pdk-publish-policies.adoc[Upload Custom Policies to Exchange]
The guidance on gerunds is here: https://confluence.internal.salesforce.com/display/MTDT/MuleSoft+CX+Writing+Style+Reference#MuleSoftCXWritingStyleReference-gerundtitles
https://raw.githubusercontent.com/mulesoft/docs-team-wiki/master/content-templates/multi-task.adoc?token=GHSAT0AAAAAACCXRJMAYTMOINZSNZLHMREWZF2WIYQ

The guidance is use gerunds for "multi-tasks" topics - a file with multiple tasks. And imperative for each H2 in the file. 
Some people shorten their TOC titles, but the guidance has never been to make those imperative (AFAIK). Please let me know where you find this!

2023-07-21 17:30 UTC, hannanelson approved these changes

2023-07-21 17:31 UTC, merged