[W-17006783][PDK] Client ID Enforcement public documentation
mulesoft/docs-gateway pull request #701
Opened 2024-11-15 18:01 UTC by andytesti

# Writer's Quality Checklist

Before merging your PR, did you:

- [ ] Run spell checker
- [ ] Run link checker to check for broken xrefs
- [ ] Check for orphan files
- [ ] Perform a local build and do a final visual check of your content, including checking for:
  - Broken images
  - Dead links
  - Correct rendering of partials if they are used in your content
  - Formatting issues, such as:
    - Misnumbered ordered lists (steps) or incorrectly nested unordered lists
    - Messed up tables
    - Proper indentation
    - Correct header levels
- [ ] Receive final review and signoff from:
  - Technical SME
  - Product Manager
  - Editor or peer reviewer
  - Reporter, if this content is in response to a reported issue (internal or external feedback)
- [ ] If applicable, verify that the software actually got released

2024-11-15 18:06 UTC, JaatadiaMulesoft requested changes

2024-11-15 18:06 UTC, JaatadiaMulesoft commented on pdk/1.3/modules/ROOT/pages/policies-pdk-configure-features-contracts.adoc
> +   pub fn authenticate(client_id: &ClientId, client_secret: &ClientSecret) -> Result<ClientData, AuthenticationError>;
same function twice, missing authorize

2024-11-15 18:11 UTC, JaatadiaMulesoft approved these changes

2024-11-20 18:49 UTC, marinasasso commented on pdk/1.3/modules/ROOT/pages/policies-pdk-configure-features-contracts.adoc
> +An authorization request filter could be written in a similar way:
```suggestion
An authorization request filter can be written in a similar way:
```

2024-11-20 18:49 UTC, marinasasso approved these changes

2024-11-20 18:49 UTC, merged