W-17117150 Create gateway
mulesoft/docs-gateway pull request #727
Opened 2024-11-27 15:30 UTC by glenn-rodgers-sf

# Writer's Quality Checklist

Before merging your PR, did you:

- [ ] Run spell checker
- [ ] Run link checker to check for broken xrefs
- [ ] Check for orphan files
- [ ] Perform a local build and do a final visual check of your content, including checking for:
  - Broken images
  - Dead links
  - Correct rendering of partials if they are used in your content
  - Formatting issues, such as:
    - Misnumbered ordered lists (steps) or incorrectly nested unordered lists
    - Messed up tables
    - Proper indentation
    - Correct header levels
- [ ] Receive final review and signoff from:
  - Technical SME
  - Product Manager
  - Editor or peer reviewer
  - Reporter, if this content is in response to a reported issue (internal or external feedback)
- [ ] If applicable, verify that the software actually got released

2024-12-04 15:51 UTC, Crispy-Salesforce approved these changes, later dismissed

2024-12-05 18:35 UTC, Pgarrett requested changes

2024-12-05 18:35 UTC, Pgarrett commented on mule-gateway/modules/ROOT/pages/mule-gateway-capabilities-mule4.adoc
> +|Policy |Version
Proxy

2024-12-05 18:35 UTC, Pgarrett commented on mule-gateway/modules/ROOT/pages/mule-gateway-capabilities-mule4.adoc
> +|===
First versions actually are:
- HTTP and HTTPS Proxy: 2.1.0
- REST: 2.2.1, 3.2.1
- WSDL: 2.2.1, 3.1.1

2024-12-05 20:36 UTC, Pgarrett approved these changes, later dismissed

2024-12-06 01:11 UTC, kevintroller approved these changes

2024-12-06 01:11 UTC, merged

2024-12-06 17:12 UTC, hannanelson commented on gateway/1.7/modules/ROOT/pages/flex-review-prerequisites.adoc
> +Hyperforce supports Flex Gateway versions 1.7 and later. Because Flex Gateway running in Local Mode is completely self-hosted, it is not affected by Hyperforce. For Flex Gateway running in Connected
Global: change "is not" to "isn't".

2024-12-06 17:12 UTC, hannanelson commented on gateway/1.7/modules/ROOT/pages/flex-review-prerequisites.adoc
> +Hyperforce supports Flex Gateway versions 1.7 and later. Because Flex Gateway running in Local Mode is completely self-hosted, it is not affected by Hyperforce. For Flex Gateway running in Connected
Consider making this a partial since it's reused.

2024-12-06 17:13 UTC, hannanelson commented on gateway/1.7/modules/ROOT/pages/flex-use-api-alerts.adoc
> +Hyperforce deployments don't support API Alerts. To learn more, see xref:api-manager::latest-overview-concept.adoc#APIM-hyperforce[API Manager on Hyperforce]
Consider making these partials and reusing between versions.

2024-12-06 17:13 UTC, hannanelson commented on mule-gateway/modules/ROOT/pages/mule-gateway-capabilities-mule4.adoc
> +All Mule Gateway proxies are supported on Hyperforce. See the following table to find the first proxy versions that are supported on Hyperforce:
Change "the following" to "this"

2024-12-06 17:14 UTC, hannanelson commented on mule-gateway/modules/ROOT/pages/mule-gateway-capabilities-mule4.adoc
> +All Mule Gateway policies are supported on Hyperforce. See the following table to find the first policy definition and implementation versions that are supported on Hyperforce:
Global: search for "the following"